### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by pptxman** [svenito92/ppSlideExtract#1]
Hello, I get this error with every pptx I try to extract
<img width="482" alt="Screen Shot 2020-08-24 at 10 56 11" src="https://user-images.githubusercontent.com/44065778/91019028-0ca55280-e5f9-11ea-953f-b7d83db342c8.png">
Windows 10 Pro 19041.450
MS Office 365 latest updates installed

**Comment by svenwanzenried** [comment]
Hi Damilola2
Could you please provide me with following additional information:
- "Detail" tab expanded in this error message
- Content of directory "C:\Users\x\Documents\New folder\" when error occurs
- Screenshot of ppSlideExtract before you click the Extract button
